// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBc0jmVesogUWD3xA_Lx7inG5HSvpel4',
    appId: '1:574319430640:web:270dbb3e739bd0ee872b35',
    messagingSenderId: '574319430640',
    projectId: 'bamx-db',
    authDomain: 'bamx-db.firebaseapp.com',
    storageBucket: 'bamx-db.appspot.com',
    measurementId: 'G-D3195XZHX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWAUyIMUIR057JgBohCYIjiEvJbYzD_6I',
    appId: '1:574319430640:android:8006e92f068ad0cb872b35',
    messagingSenderId: '574319430640',
    projectId: 'bamx-db',
    storageBucket: 'bamx-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEJUW7t1q1VfBBmoeY20YODbXfzHZ8Oek',
    appId: '1:574319430640:ios:d2440a92e7828397872b35',
    messagingSenderId: '574319430640',
    projectId: 'bamx-db',
    storageBucket: 'bamx-db.appspot.com',
    iosBundleId: 'com.example.bancoAlimentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEJUW7t1q1VfBBmoeY20YODbXfzHZ8Oek',
    appId: '1:574319430640:ios:b8b2a26a4ffdef78872b35',
    messagingSenderId: '574319430640',
    projectId: 'bamx-db',
    storageBucket: 'bamx-db.appspot.com',
    iosBundleId: 'com.example.bancoAlimentos.RunnerTests',
  );
}
